/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2014-12-13 06:29:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MyCal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");

		String num1 = request.getParameter("num1");
		String num2 = request.getParameter("num2");
		String flag = request.getParameter("flag");
		int sum = 0;
		int n1 = 0;
		int n2 = 0;
		if(num1 != null && num2 != null && flag != null){
		n1 = Integer.parseInt(num1);
		n2 = Integer.parseInt(num2);
			if(flag.equals("+")){
				sum = n1 + n2;
			}else if(flag.equals("-")){
				sum = n1 - n2;
			}else if(flag.equals("*")){
				sum = n1 * n2;
			}else{
				sum = n1 / n2;
			}
		}
	
      out.write("\n");
      out.write("\t<form action=\"MyCal.jsp\" method = \"post\">\n");
      out.write("\t\t<input type = \"text\" name = \"num1\" value = \"");
      out.print( n1);
      out.write("\">\n");
      out.write("\t\t<select name = \"flag\">\n");
      out.write("\t\t\t<option>+</option>\n");
      out.write("\t\t\t<option>-</option>\n");
      out.write("\t\t\t<option>*</option>\n");
      out.write("\t\t\t<option>/</option>\n");
      out.write("\t\t</select>\n");
      out.write("\t\t<input type = \"text\" name = \"num2\" value = \"");
      out.print( n2);
      out.write("\">\n");
      out.write("\t\t<input type = \"submit\" value = \"send\">\n");
      out.write("\t</form>\n");
      out.write("\t计算结果是");
      out.print( sum );
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
